server:
  port: 8083

spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: ${ancy.datasource.driver-class-name}
      url: jdbc:mysql://${ancy.datasource.host}:${ancy.datasource.port}/${ancy.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${ancy.datasource.username}
      password: ${ancy.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ancy.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
